mod gallery;
pub use gallery::About;
mod hero;
pub use hero::Hero;
mod navbar;
pub use navbar::Navbar;
mod projects;
pub use projects::Projects;
mod timeline;
pub use timeline::Timeline;
mod links;
pub use links::Links;
